# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f57fb91c2fbf28422bb265bb16b54755"
application_url = "https://reportes-store-bm.vercel.app/"
embedded = true
name = "reportes-store-bm"
handle = "reportes-store-bm"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pruebas-equipo-web.myshopify.com"
include_config_on_deploy = true

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_pixels,read_customer_events"

[auth]
redirect_urls = [ "https://reportes-store-bm.vercel.app/api/auth" ]

[pos]
embedded = false
