# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "22126b204b9b804f175588ea775aa94d"
application_url = "https://involve-labs-antivirus-ea.trycloudflare.com"
embedded = true
name = "pixelote"
handle = "pixelote"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "pruebas-equipo-web.myshopify.com"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://involve-labs-antivirus-ea.trycloudflare.com/auth/callback",
  "https://involve-labs-antivirus-ea.trycloudflare.com/auth/shopify/callback",
  "https://involve-labs-antivirus-ea.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
